name: Java CI with Maven and Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # 👇 Add permissions for pull request comments
    permissions:
      pull-requests: write  # Required for sticky-pull-request-comment
      contents: read        # Default permissions

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test with Maven
        run: mvn clean test package --file pom.xml

      - name: Upload Jacoco HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Extract Jacoco Coverage Percentage
        id: extract-coverage
        run: |
          sudo apt-get update && sudo apt-get install -y xmlstarlet
          COVERAGE_RATIO=$(xmlstarlet sel -T -t -m "/report/counter[@type='INSTRUCTION']" \
            -v "concat(@covered, '/', (number(@covered) + number(@missed)))" \
            -n target/site/jacoco/jacoco.xml)
          echo "Extracted coverage ratio: $COVERAGE_RATIO"
          IFS='/' read -r COVERED TOTAL <<< "$COVERAGE_RATIO"
          PERCENT=$(echo "scale=2; $COVERED*100/$TOTAL" | bc)
          echo "totalCoverage=$PERCENT" >> "$GITHUB_OUTPUT"
          echo "Overall Coverage Percentage is: $PERCENT%"

      - name: Comment on PR with Coverage Details
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "Jacoco Coverage Report"
          message: |
            **Total Coverage:** ${{ steps.extract-coverage.outputs.totalCoverage }}%