name: Java CI with Maven and Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up JDK 17 and cache Maven dependencies
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Build and run tests; Jacoco report is generated in the test phase.
      - name: Build and Test with Maven
        run: mvn clean test package --file pom.xml

#      # (Optional) Update dependency graph for improved Dependabot alerts
#      - name: Update dependency graph
#        uses: advanced-security/maven-dependency-submission-action@v3

      # Upload the generated Jacoco HTML report as an artifact
      - name: Upload Jacoco HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      # Extract overall coverage percentage from the generated Jacoco XML report
      - name: Extract Jacoco Coverage Percentage
        id: extract-coverage
        run: |
          # Install xmlstarlet to parse the XML report
          sudo apt-get update && sudo apt-get install -y xmlstarlet
          # Parse jacoco.xml file for 'INSTRUCTION' counter values
          COVERAGE_RATIO=$(xmlstarlet sel -T -t -m "/report/counter[@type='INSTRUCTION']" \
            -v "concat(@covered, '/', (number(@covered) + number(@missed)))" \
            -n target/site/jacoco/jacoco.xml)
          echo "Extracted coverage ratio: $COVERAGE_RATIO"
          IFS='/' read -r COVERED TOTAL <<< "$COVERAGE_RATIO"
          # Calculate percentage with 2 decimals
          PERCENT=$(echo "scale=2; $COVERED*100/$TOTAL" | bc)
          echo "totalCoverage=$PERCENT" >> "$GITHUB_OUTPUT"
          echo "Overall Coverage Percentage is: $PERCENT%"

      # Post/update a PR comment with the overall coverage percentage (only runs on pull_request events)
      - name: Comment on PR with Coverage Details
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "Jacoco Coverage Report"
          message: |
            **Total Coverage:** ${{ steps.extract-coverage.outputs.totalCoverage }}%