name: Java CI with Maven and Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Get base branch coverage (master)
      - name: Checkout base branch for comparison
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin master:master
          git checkout master
          mvn test -DskipTests --file pom.xml

      # Fix DTD loading issue by disabling XML validation
      - name: Disable XML validation for Jacoco
        run: |
          sed -i 's|<!DOCTYPE report PUBLIC "-//JACOCO//DTD Report 1.1//EN" "report.dtd">||' target/site/jacoco/jacoco.xml

      # Run tests on current branch
      - name: Build and Test with Maven
        run: mvn clean test package --file pom.xml

      # Compare coverage between branches
      - name: Compare Coverage
        if: github.event_name == 'pull_request'
        id: compare-coverage
        run: |
          # Install dependencies
          sudo apt-get update && sudo apt-get install -y xmlstarlet bc

          # Fix DTD loading issue again for current branch
          sed -i 's|<!DOCTYPE report PUBLIC "-//JACOCO//DTD Report 1.1//EN" "report.dtd">||' target/site/jacoco/jacoco.xml

          # Get base branch (master) coverage
          BASE_COV=$(xmlstarlet sel -T -t -m "/report/counter[@type='INSTRUCTION']" \
            -v "concat(@covered, '/', (number(@covered) + number(@missed)))" \
            -n target/site/jacoco/jacoco.xml || echo "0/1")
          IFS='/' read -r BASE_COVERED BASE_TOTAL <<< "$BASE_COV"
          BASE_PERCENT=$(echo "scale=2; $BASE_COVERED*100/$BASE_TOTAL" | bc)

          # Get current branch coverage
          CURRENT_COV=$(xmlstarlet sel -T -t -m "/report/counter[@type='INSTRUCTION']" \
            -v "concat(@covered, '/', (number(@covered) + number(@missed))" \
            -n target/site/jacoco/jacoco.xml || echo "0/1")
          IFS='/' read -r CURRENT_COVERED CURRENT_TOTAL <<< "$CURRENT_COV"
          CURRENT_PERCENT=$(echo "scale=2; $CURRENT_COVERED*100/$CURRENT_TOTAL" | bc)

          # Calculate difference
          DIFF=$(echo "$CURRENT_PERCENT - $BASE_PERCENT" | bc)
          echo "baseCoverage=$BASE_PERCENT" >> $GITHUB_OUTPUT
          echo "currentCoverage=$CURRENT_PERCENT" >> $GITHUB_OUTPUT
          echo "coverageDiff=$DIFF" >> $GITHUB_OUTPUT

          MIN_COVERAGE=85
          if (( $(echo "$CURRENT_PERCENT < $MIN_COVERAGE" | bc -l) )); then
            echo "::warning::Test coverage ($CURRENT_PERCENT%) is below recommended minimum ($MIN_COVERAGE%)"
          fi

          echo "Coverage: Base=$BASE_PERCENT% Current=$CURRENT_PERCENT% (Change: $DIFF%)"

      - name: Upload Jacoco HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Comment on PR with Coverage Details
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "Jacoco Coverage Report"
          message: |
            **Coverage Analysis**
            - Base Branch (master): ${{ steps.compare-coverage.outputs.baseCoverage }}%
            - Current Branch: ${{ steps.compare-coverage.outputs.currentCoverage }}%
            - Change: ${{ steps.compare-coverage.outputs.coverageDiff }}%
            
            {{ if(contains(steps.compare-coverage.outputs.currentCoverage, '85')) }}
            ✅ **PASSED**: Coverage meets 85% target
            {{ else }}
            ⚠️ **WARNING**: Coverage (${{ steps.compare-coverage.outputs.currentCoverage }}%) is below 85% target
            {{ endif }}