name: PR Build and Test with Jacoco

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        # Using version 3.6.0 as per your logs

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build and Test
        run: mvn clean test

      - name: Upload Jacoco HTML Report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Extract Jacoco Coverage Percentage
        id: extract-coverage
        run: |
          # Install xmlstarlet to parse XML
          sudo apt-get update && sudo apt-get install -y xmlstarlet
          # Extract the 'INSTRUCTION' counter information from the jacoco.xml report.
          COVERAGE_RATIO=$(xmlstarlet sel -T -t -m "/report/counter[@type='INSTRUCTION']" -v "concat(@covered, '/', (number(@covered) + number(@missed)))" -n target/site/jacoco/jacoco.xml)
          echo "Extracted coverage ratio: $COVERAGE_RATIO"
          IFS='/' read -r COVERED TOTAL <<< "$COVERAGE_RATIO"
          # Calculate percentage (with two decimals precision)
          PERCENT=$(echo "scale=2; $COVERED*100/$TOTAL" | bc)
          echo "totalCoverage=$PERCENT" >> "$GITHUB_OUTPUT"
          echo "Overall Coverage Percentage is: $PERCENT%"

      - name: Comment on PR with Coverage Details
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "Jacoco Coverage Report"
          message: |
            **Total Coverage:** ${{ steps.extract-coverage.outputs.totalCoverage }}%
