name: Java CI with Maven and Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Generate Coverage for PR Branch
        run: |
          mvn clean test
          mkdir -p coverage/pr
          cp target/site/jacoco/jacoco.xml coverage/pr/
          cp -r target/site/jacoco coverage/pr/html

      - name: Checkout Base Branch (master)
        run: |
          git fetch origin master
          git checkout origin/master
          mvn clean test
          mkdir -p coverage/base
          cp target/site/jacoco/jacoco.xml coverage/base/
          cp -r target/site/jacoco coverage/base/html

      - name: Compare Coverage
        id: compare
        run: |
          sudo apt-get update && sudo apt-get install -y xmlstarlet bc

          BASE_COV=$(xmlstarlet sel -t -v "concat(/report/counter[@type='INSTRUCTION']/@covered, '/', (/report/counter[@type='INSTRUCTION']/@covered + /report/counter[@type='INSTRUCTION']/@missed))" coverage/base/jacoco.xml)
          PR_COV=$(xmlstarlet sel -t -v "concat(/report/counter[@type='INSTRUCTION']/@covered, '/', (/report/counter[@type='INSTRUCTION']/@covered + /report/counter[@type='INSTRUCTION']/@missed))" coverage/pr/jacoco.xml)

          IFS='/' read -r BASE_COVERED BASE_TOTAL <<< "$BASE_COV"
          IFS='/' read -r PR_COVERED PR_TOTAL <<< "$PR_COV"

          BASE_PERCENT=$(echo "scale=2; 100 * $BASE_COVERED / $BASE_TOTAL" | bc)
          PR_PERCENT=$(echo "scale=2; 100 * $PR_COVERED / $PR_TOTAL" | bc)
          DIFF=$(echo "scale=2; $PR_PERCENT - $BASE_PERCENT" | bc)

          echo "baseCoverage=$BASE_PERCENT" >> $GITHUB_OUTPUT
          echo "prCoverage=$PR_PERCENT" >> $GITHUB_OUTPUT
          echo "coverageDiff=$DIFF" >> $GITHUB_OUTPUT

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "Jacoco Coverage Report"
          message: |
            **Coverage Comparison**
            - Base Branch (master): ${{ steps.compare.outputs.baseCoverage }}%
            - Current PR: ${{ steps.compare.outputs.prCoverage }}%
            - Difference: ${{ steps.compare.outputs.coverageDiff }}%

            ${{ steps.compare.outputs.prCoverage >= 85 && '✅ Coverage meets target' || '⚠️ Coverage is below target (85%)' }}
